# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.TOKEN }}
          ref: bug-fix-tests
      - name: Run a one-line script
        run: ls ImageRecognision/Model
      - uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
        #id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "https://github.com/onnx/models/raw/main/validated/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-10.onnx?download="
        #  url: ${{ secrets.ULR }} 
          target: ImageRecognision/Model/
      - name: Run a one-line script
        run: ls ImageRecognision/Model
        # Invoke-WebRequest
    #  - name: download 
     #   run: curl ${{ secrets.ULR }} 
    #  - name: Download a file
   #     uses: Minionguyjpro/Download-File-Action@v1
  #      with:
    # URL to file
 #         url: "https://github.com/onnx/models/raw/main/validated/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-10.onnx?download="
    # Target path
#          target-path: ./ImageRecognision/Model
      # Runs a single command using the runners shell
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"
      
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test 
        #--no-build --verbosity normal
 
