# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.TOKEN }}
      - name: Run a one-line script
        run: ls 
      - name: Download a file
  # You may pin to the exact commit or the version.
  # uses: valitydev/action-download-file@7fb017bf38a45a6d420e5456e95f0b1ef966a20c
        uses: valitydev/action-download-file@v1.0.6
        with:
    # URL to file
          url: "https://github.com/onnx/models/raw/main/validated/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-10.onnx?download="
    # Target path
          target-path: ./ImageRecognision/Model
      # Runs a single command using the runners shell
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"
      
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
