name: Clear all Github actions caches 
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: 'false'
