name: team

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  windowsrunner:
    timeout-minutes: 500
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
     GH_TOKEN: ${{ secrets.TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: pwsh
        run: |
          
          
          docker run -d --name teamcity-agent \
          -e SERVER_URL="${{secrets.TEAM}}" \
          -e AGENT_NAME="windows" \
          -v "C:\path\to\your\Agent_WorkDir:C:\BuildAgent\work" \
          jetbrains/teamcity-agent:latest-windowsservercore
            docker logs -f teamcity-agent

            sleep 1000
